name: Build & Production
on:
  push:
    tags:
      - 'release-*'
    branches:
      - master

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  SERVICE_PORT: 80

jobs:
  build:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-production
          DOCKER_BUILD_ARG_REACT_APP_AUTHENTICATED: 'no'
          DOCKER_BUILD_ARG_REACT_APP_API_URL: 'https://puistotalkoot-api.prod.kuva.hel.ninja'
          DOCKER_BUILD_ARG_REACT_APP_OPENID_CLIENT_ID: 'http://id.hel.fi/apps/prod/harava-ui'
          DOCKER_BUILD_ARG_REACT_APP_SSO_URL: 'https://api.hel.fi/sso'
          DOCKER_BUILD_ARG_REACT_APP_OPEN_ID_API_TOKENS_SCOPE: 'https://api.hel.fi/auth/puistotalkoot'
          DOCKER_BUILD_ARG_REACT_APP_GEOCODER_API_URL: 'https://api.digitransit.fi/geocoding/v1/'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_URL_BASE: 'https://analytics.hel.ninja/'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SITE_ID: 65
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_ENABLED: 'true'

  production:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          K8S_ADDITIONAL_HOSTNAMES: ${{ secrets.ADDITIONAL_HOSTNAMES }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-production
